// Widget tests for the gallery-tile preview page.
//
// What we cover:
//   1. [extractMp4Range] (pure helper): byte-range correctness across
//      buffer boundaries; rejects inverted / empty range.
//   2. Non-motion-photo long-press surfaces the '该图片无视频段' pill and
//      never creates a video_player controller.
//   3. Oversized file shows '文件过大，无法预览' banner and the sandbox
//      MethodChannel is never invoked.
//
// What we deliberately do NOT cover here:
//   - Actual motion-photo extract + playback path. `VideoPlayerController.file`
//     requires a real platform decoder; in the flutter_test harness its
//     `.initialize()` future never resolves, which hangs any widget test
//     that awaits it. The pure-helper test (#1) + the smoke tool
//     (`tool/extract_mp4_smoke.dart`) jointly cover the byte-extract
//     side; on-device playback is covered by manual QA and will be
//     wired into an integration_test once real Motion Photos land in
//     the device's MediaStore.
//
// The Android MediaStore channel is mocked via TestDefaultBinaryMessenger
// — same pattern mediastore_channel_test.dart uses. No mocktail required
// for the boundary we're testing.

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:liveback/core/constants.dart';
import 'package:liveback/core/theme.dart';
import 'package:liveback/features/preview/preview_page.dart';
import 'package:liveback/l10n/generated/app_localizations.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  const channelName = LivebackConstants.channelMediaStore;
  final messenger =
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;

  // Fixture files shipped at test/fixtures/samples/ (generated by
  // tool/gen_sample_fixtures.dart; see test/fixtures/README.md).
  final noMp4Fixture = File('test/fixtures/samples/no_mp4.jpg');

  tearDown(() {
    messenger.setMockMethodCallHandler(
      const MethodChannel(channelName),
      null,
    );
  });

  /// Installs a mock that returns [sandboxPath] for any copyInputToSandbox
  /// call and no-ops on releaseSandbox.
  void installMock(String sandboxPath) {
    messenger.setMockMethodCallHandler(
      const MethodChannel(channelName),
      (call) async {
        if (call.method == 'copyInputToSandbox') {
          return <String, dynamic>{'path': sandboxPath};
        }
        if (call.method == 'deleteSandboxFiles') {
          return null;
        }
        return null;
      },
    );
  }

  /// Pumps PreviewPage inside a minimal MaterialApp that registers the
  /// brand theme (so `context.colors` works).
  Future<void> pumpPreview(
    WidgetTester tester, {
    required String contentUri,
    required String displayName,
    required int sizeBytes,
  }) async {
    await tester.pumpWidget(
      MaterialApp(
        theme: LivebackTheme.light(),
        darkTheme: LivebackTheme.dark(),
        // Pin zh so the assertions below keep their original expected
        // strings (the test was authored pre-i18n against zh copy).
        locale: const Locale('zh'),
        supportedLocales: const [Locale('en'), Locale('zh')],
        localizationsDelegates: const [
          AppL10n.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        home: PreviewPage(
          args: PreviewPageArgs(
            contentUri: contentUri,
            displayName: displayName,
            sizeBytes: sizeBytes,
          ),
        ),
      ),
    );
  }

  group('extractMp4Range', () {
    test('copies exact byte range via buffered stream', () async {
      final tmp = await Directory.systemTemp.createTemp('liveback-extract-');
      try {
        final src = File('${tmp.path}/src.bin');
        final dst = '${tmp.path}/dst.bin';
        // 600 KB of incrementing bytes so boundary issues show up as diffs.
        const len = 600 * 1024;
        final bytes = List<int>.generate(len, (i) => i & 0xFF);
        await src.writeAsBytes(bytes, flush: true);

        const start = 123;
        const end = 123 + 512 * 1024; // straddles two 256 KB buffer pulls
        final written = await extractMp4Range(
          srcPath: src.path,
          mp4Start: start,
          mp4End: end,
          dstPath: dst,
        );
        expect(written, end - start);
        final out = await File(dst).readAsBytes();
        expect(out.length, end - start);
        for (var i = 0; i < out.length; i++) {
          expect(out[i], bytes[start + i],
              reason: 'mismatch at byte $i (abs ${start + i})');
        }
      } finally {
        await tmp.delete(recursive: true);
      }
    });

    test('rejects empty / inverted range', () async {
      final tmp = await Directory.systemTemp.createTemp('liveback-extract-');
      try {
        final src = File('${tmp.path}/src.bin');
        await src.writeAsBytes(const [1, 2, 3, 4], flush: true);
        await expectLater(
          extractMp4Range(
            srcPath: src.path,
            mp4Start: 2,
            mp4End: 2,
            dstPath: '${tmp.path}/dst.bin',
          ),
          throwsA(isA<ArgumentError>()),
        );
      } finally {
        await tmp.delete(recursive: true);
      }
    });
  });

  testWidgets(
    'non-motion-photo long-press surfaces 无视频段 pill, never creates a video',
    (tester) async {
      expect(noMp4Fixture.existsSync(), isTrue,
          reason: 'missing fixture ${noMp4Fixture.path}');
      installMock(noMp4Fixture.absolute.path);

      await pumpPreview(
        tester,
        contentUri: 'content://media/external/images/media/42',
        displayName: 'no_mp4.jpg',
        sizeBytes: noMp4Fixture.lengthSync(),
      );

      // Drive frames WITHOUT pumpAndSettle: the page's self-scheduling
      // 2-second timers will never go quiescent. Several pumps with
      // small delays flush the sandbox mock + parser future.
      for (var i = 0; i < 6; i++) {
        await tester.pump(const Duration(milliseconds: 50));
      }

      // The round play button must never show for a non-motion-photo —
      // the pill was removed entirely and the button is gated on
      // isMotionPhoto.
      expect(
        find.byIcon(Icons.play_arrow),
        findsNothing,
        reason: 'play button must not surface for non-motion-photo inputs',
      );

      // Long-press somewhere on the preview. kLongPressTimeout = 500 ms.
      final center = tester.getCenter(find.byType(PreviewPage));
      final gesture = await tester.startGesture(center);
      await tester.pump(const Duration(milliseconds: 600));

      expect(find.text('该图片无视频段'), findsOneWidget);
      // No VideoPlayer widget ever got attached.
      expect(
        find.byWidgetPredicate(
            (w) => w.runtimeType.toString() == 'VideoPlayer'),
        findsNothing,
      );

      await gesture.up();
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));
      expect(find.text('该图片无视频段'), findsNothing);
    },
  );

  testWidgets('oversized file shows 文件过大 banner and never calls sandbox',
      (tester) async {
    var copyCalls = 0;
    messenger.setMockMethodCallHandler(
      const MethodChannel(channelName),
      (call) async {
        if (call.method == 'copyInputToSandbox') {
          copyCalls += 1;
        }
        return null;
      },
    );

    await pumpPreview(
      tester,
      contentUri: 'content://media/external/images/media/99',
      displayName: 'huge.jpg',
      sizeBytes: LivebackConstants.maxFileSizeBytes + 1,
    );
    // The oversized path synchronously flags in initState; a single pump
    // renders the banner.
    await tester.pump();

    expect(find.text('文件过大，无法预览'), findsOneWidget);
    expect(copyCalls, 0);
  });
}
